language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y libprotobuf-dev
script: ./bootstrap.sh && ./configure && make
