language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install protobuf-compiler && sudo apt-get install libprotobuf-dev; fi
script: ./bootstrap.sh && configure && make
os:
  - linux
  - osx
