language: cpp
compiler:
- gcc
- clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y protobuf-compiler libprotobuf-dev
script: ./bootstrap.sh && ./configure --with-protobuf=/usr/ && make
notifications:
  email:
    recipients:
      - ondovb@nbacc.net
      - treangent@nbacc.net
    on_success: change
    on_failure: always
os:
  - linux
deploy:
  provider: releases
  api_key:
    secure: h82kGW1iD80xXArooopp330Arr7nzuhOFlYpn9wjrcNXJzaGom2aKMTatb2pfGCrWFItsTTjoJCItN9TQto5CMtXE3lQhHxhw/Eotzshu0FsuxYk9KkixByZHnC7eDP4BpZKMJE74sjAYDUn0BgqL49xSL6+p4pak+cNZP7kxSk=
  file: harvest
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: marbl/harvest-tools
